USE [PROJETO INTEGRADO]


CREATE TABLE CLIENTES (
	CLIENTE_ID  INT PRIMARY KEY,
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	TELEFONE VARCHAR (20)
);


CREATE TABLE PRODUTOS (
	PRODUTO_ID INT PRIMARY KEY,
	NOME VARCHAR(100),
	CATEGORIA VARCHAR(50),
	PRECO DECIMAL(10,2)
);

CREATE TABLE VENDAS (
    VENDA_ID INT PRIMARY KEY,
    CLIENTE_ID INT REFERENCES CLIENTES(CLIENTE_ID),
    PRODUTO_ID INT REFERENCES PRODUTOS(PRODUTO_ID),
    DATA_VENDA DATE,
    QUANTIDADE INT CHECK (QUANTIDADE > 0)
);


CREATE TABLE PAGAMENTOS (
	PAGAMENTO_ID INT PRIMARY KEY,
	VENDA_ID INT REFERENCES VENDAS(VENDA_ID),
	DATA_PAGAMENTO DATE,
	VALOR_PAGAMENTO DECIMAL(10,2),
	METODO_PAGAMENTO VARCHAR(50)
);

